# Generated by Django 3.1.3 on 2020-11-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='payment_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Extended', 'Extended'), ('Advanced', 'Advanced'), ('Medium', 'Medium'), ('Basic', 'Basic'), ('Free', 'Free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_membership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='web.usermembership'),
        ),
    ]
