# Generated by Django 3.1.3 on 2020-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201108_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='paystack_access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='paystack_charge_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
