# Generated by Django 3.1.3 on 2020-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_payhistory_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
